<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 ./stones.glb -t
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      BIG_1_BiG_0: THREE.Mesh
      Big_2_BiG_0: THREE.Mesh
    }
    materials: {
      material_1: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/stones.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.BIG_1_BiG_0.geometry}
      material={gltf.materials.material_1}
      position={[0, 0.9, 0]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={0.03}
    />
    <T.Mesh
      geometry={gltf.nodes.Big_2_BiG_0.geometry}
      material={gltf.materials.material_1}
      position={[0, 0.9, 0]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={0.03}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
